### ISSUE TITLE
Migrate to java 17

### ISSUE THREAD

**Issue by The4thLaw** [The4thLaw/demyo#158]
Java 17 has been out for a while now and has even reached Debian stable. It's becoming a requirement for the latest version of some libraries and could become the baseline for Demyo.

The migration should include:
- [x] A migration to the java.nio APIs (for Path, for example) (actually already in Java 8)
- [x] Using records for some POJOs (https://openjdk.org/jeps/395)
- [x] Pattern matching for instanceof (https://openjdk.org/jeps/394)
- [x] Better collectors like https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/stream/Stream.html#toList()
- [x] `var` typed variables (https://openjdk.org/jeps/286) ?
- [x] Collection factory methods (https://openjdk.org/jeps/269)
- [x] `forRemoval` deprecation (https://openjdk.org/jeps/277)
- [x] Get rid of some Apache Commons calls which have a Java 17 equivalent (like FileUtils.write or FileUtils.readFileToString)
- [x] Removing the Java 8 build from the GitHub actions
- [x] Updating some libraries depending on the effort (Spring, Hibernate and Jetty come to mind)

**Comment by Fiend-Star-666** [comment]
Hi The4thLaw, Is this issue open for all to contribute?

if yes, then I'm having issues in getting some of the dependencies due to a 401 error:

Could not transfer artifact org.the4thlaw:common-utils:pom:1.2.0 from/to github-the4thlaw (https://maven.pkg.github.com/The4thLaw/*): status code: 401, reason phrase: Unauthorized (401)

**Comment by The4thLaw** [comment]
Hello,

It's very nice of you to offer but no, it's something I've already started to work on and will continue.

With regards to the 401 error, it's a limitation of the GitHub API. You need a token that has a read access to packages. More on that here:
 - https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages#permissions-for-repository-scoped-packages
 - https://stackoverflow.com/q/60400637/109813

I'm currently wondering whether I should publish to Maven Central but it's a bit more work so I'm not sure when it would be done.

**Comment by The4thLaw** [comment]
Merged to master
